spring:
  application:
    name: code-generator
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://:3306/code_generator?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username: xxx
    password: xxx
    port: 465
    properties:
      mail:
        imap:
          ssl:
            socketFactory:
              fallback: false
        smtp:
          auth: false
          ssl:
            enable: false
            socketFactory:
              class: com.fintech.modules.base.util.mail.MailSSLSocketFactory
          starttls:
            enable: false
            required: false
    test-connection: false
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 9999

cn:
  iba8:
    module:
      generator:
        input-dir: D:/i/my/data/input
        output-dir: D:/i/my/data/output
        input-history: D:/i/my/data/inputHistory
        code-output-tmp: D:/i/my/code/output
      cron:
        database-monitor: 0 0/5 * * * ?
        database-change-push: 0 0/1 * * * ?
        table-change-push: 0 0/1 * * * ?
